# Generated by Django 2.1.7 on 2019-02-17 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0002_auto_20190214_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/%y/%m/%d/'),
        ),
    ]
